builds:
  - id: casket
    main: main.go
    dir: ./casket
    binary: casket
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
  # Build specifically for the Docker image with CGO disabled for MUSL compatibility
  - id: docker
    main: main.go
    dir: ./casket
    binary: casket
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - ids:
      - docker
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile.release
    image_templates:
      - "ghcr.io/tmpim/casket:latest-amd64"
      - "ghcr.io/tmpim/casket:{{ .Tag }}-amd64"
      - "ghcr.io/tmpim/casket:v{{ .Major }}-amd64"
      - "ghcr.io/tmpim/casket:v{{ .Major }}.{{ .Minor }}-amd64"
  - ids:
      - docker
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile.release
    image_templates:
      - "ghcr.io/tmpim/casket:latest-arm64"
      - "ghcr.io/tmpim/casket:{{ .Tag }}-arm64"
      - "ghcr.io/tmpim/casket:v{{ .Major }}-arm64"
      - "ghcr.io/tmpim/casket:v{{ .Major }}.{{ .Minor }}-arm64"

docker_manifests:
- name_template: ghcr.io/tmpim/casket:latest
  image_templates:
  - ghcr.io/tmpim/casket:latest-amd64
  - ghcr.io/tmpim/casket:latest-arm64
- name_template: ghcr.io/tmpim/casket:{{ .Tag }}
  image_templates:
  - ghcr.io/tmpim/casket:{{ .Tag }}-amd64
  - ghcr.io/tmpim/casket:{{ .Tag }}-arm64
- name_template: ghcr.io/tmpim/casket:v{{ .Major }}
  image_templates:
  - ghcr.io/tmpim/casket:{{ .Major }}-amd64
  - ghcr.io/tmpim/casket:{{ .Major }}-arm64
- name_template: ghcr.io/tmpim/casket:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - ghcr.io/tmpim/casket:{{ .Major }}.{{ .Minor }}-amd64
  - ghcr.io/tmpim/casket:{{ .Major }}.{{ .Minor }}-arm64

# Set dist directory to build/ since we have files in dist/
dist: build

before:
  hooks:
    - sh ./.prerelease.sh

archives:
  - id: casket
    builds:
      - casket
    format_overrides:
      - goos: windows
        format: zip
checksum:
  algorithm: sha256

release:
  github:
    owner: tmpim
    name: casket
  ids:
    - casket
  draft: true
  prerelease: auto
