name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t ./...

    - name: Build
      run: go build -v ./...

    - name: Add quic.clemente.io to /etc/hosts
      run: echo "127.0.0.1 quic.clemente.io" | sudo tee -a /etc/hosts

    - name: Test
      run: go test -v -race -parallel 6 ./...
